from abc import ABC, abstractmethod
from typing import Callable, List
from api.schemas import Instrument, Quote, OrderBook, Trade, Order, AccountInfo, Position

class ExchangeAdapter(ABC):
    @abstractmethod
    async def list_instruments(self) -> List[Instrument]: ...
    @abstractmethod
    async def subscribe_quotes(self, symbols: List[str], on_data: Callable[[Quote], None]) -> None: ...
    @abstractmethod
    async def subscribe_order_book(self, symbols: List[str], on_data: Callable[[OrderBook], None]) -> None: ...
    @abstractmethod
    async def subscribe_trades(self, symbols: List[str], on_data: Callable[[Trade], None]) -> None: ...
    @abstractmethod
    async def place_order(self, o: Order) -> Order: ...
    @abstractmethod
    async def cancel_order(self, order_id: str, symbol: str) -> Order: ...
    @abstractmethod
    async def get_account_info(self) -> AccountInfo: ...
    @abstractmethod
    async def get_positions(self) -> List[Position]: ...
    @abstractmethod
    async def get_history(self, symbol: str, tf: str, limit: int) -> list: ...
